apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortlink-server
  labels:
    app: shortlink-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shortlink-server
  template:
    metadata:
      labels:
        app: shortlink-server
    spec:
      containers:
      - name: shortlink-server
        image: shortlink-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: GO_ENV
          value: "production"
        - name: DB_DSN
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: dsn
        - name: REDIS_ADDR
          value: "redis-master:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: password
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: shortlink-server
  labels:
    app: shortlink-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: shortlink-server